[ioctl]
extents   = 128
ctl       = ""

[cache]
base  = 0
bound = 0
file  = ""

[l2cache]
base  = 0
bound = 0
file  = ""
chunksize = 0

[backend]
enabled = "object"

    [backend.file]
    file = "store.raw"

    [backend.object]
    api = "s3"
    gcMode = "on" # on | silent | off | statsOnly

    [backend.object.s3]
    bucket = "dis"
    region = "us-east-1"
    remote = "http://192.168.122.1:9000"

    [backend.object.rados]
    pool = "ec-pool"
